############################################################################
# D13x Hengshan-Pi home control panel
############################################################################

include $(APPDIR)/Make.defs

PROGNAME  = home_panel
PRIORITY  = $(CONFIG_D13X_HOME_PANEL_PRIORITY)
STACKSIZE = $(CONFIG_D13X_HOME_PANEL_STACKSIZE)
MODULE    = $(CONFIG_D13X_HOME_PANEL)

MAINSRC = home_panel_main.c
CSRCS   = home_panel_misans_18.c

include $(APPDIR)/Application.mk
